image: microsoft/dotnet:onbuild

pipelines:
  default:
    - step:
        script:
          - export PROJECT_NAME=DiscordPugBotcore
          - export TEST_NAME=DiscordPugBotcore/DiscordPugBotcore.Tests

          - dotnet restore
          - dotnet build $PROJECT_NAME
          - dotnet test $TEST_NAME
